version: '3'

services:
  tanksystem-api:
    build: .
    image: tanksystem-api
    ports:
      - '9000:9000'
    depends_on:
      - db
    restart: always
    container_name: 'home_automation_backend'
    networks:
      - network
  db:
    image: arm64v8/mongo:5.0.5-focal
    restart: always
    ports:
      - "27017:27017"
    container_name: 'mongo_db_server'
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - network

networks:
  network:
    driver: bridge
