apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      nodePort: 30000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10000
  selector:
    run: api
