apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
        - image: vickygonsalves/tanksystem-api
          imagePullPolicy: Always
          name: api
          ports:
          - containerPort: 9000
            name: http-server
      ports:
        - name: liveness-port
          containerPort: 9000
          hostPort: 9000
      livenessProbe:
        httpGet:
          path: /api/get-statuses
          port: liveness-port
        failureThreshold: 1
        periodSeconds: 10
      startupProbe:
        httpGet:
          path: /api/get-statuses
          port: liveness-port
        failureThreshold: 30
        periodSeconds: 10
