apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
        - image: vickygonsalves/tanksystem-api
          imagePullPolicy: Always
          name: api
          sessionAffinity: ClientIP
          sessionAffinityConfig:
            clientIP:
              timeoutSeconds: 10000
          ports:
          - containerPort: 9000
            hostPort: 9000
            name: http-server
          livenessProbe:
              httpGet:
                path: /api/get-statuses
                port: http-server
              failureThreshold: 1
              periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/get-statuses
              port: http-server
            failureThreshold: 30
            periodSeconds: 10
