apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
        - image: vickygonsalves/tanksystem-api
          name: api
          ports:
          - containerPort: 9000
            name: http-server
